# Site settings
title: Izabelle Mendonça
author: izabelle mendonça
description: "Izabelle Mendonça, Jornalismo e Publicidade, São Paulo"
keywords: "izabelle mendonça, izabelle mendonca, izabelle, mendonca, mendonça, jornalista, jornalismo, publicitaria, publicidade, assessoria, comunicacao, comunicação, são paulo, sao paulo"
email: izabellem2@gmail.com
phone: (11) 98594-0444

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://izabellemendonca.com" # the base hostname & protocol for your site
facebook_username:  izabelle.mendonca.3
linkedin_username:  izabellemendonca

# Build settings
markdown: kramdown
